name: Build APK with Buildozer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git python3-pip python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
        pip install buildozer cython virtualenv

    - name: Build with Buildozer
      run: |
        buildozer init
        sed -i 's/source.dir = .*/source.dir = ./' buildozer.spec
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
pkxapkx         path: bin/*.apk
