name: Build APK (Final Stable - Wajib Berhasil)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Bersihkan paksa folder buildozer (agar tidak memakai sisa build Linux yang error)
    - name: Clean build directory
      run: |
        rm -rf /home/runner/.buildozer
        rm -rf ./buildozer

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git python3-pip python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libtool libtool-bin autoconf automake pkg-config autoconf-archive

    # KUNCI UTAMA PERBAIKAN: Pakai Buildozer 1.5.0 (Versi Stabil Resmi), BUKAN versi Git
    - name: Install Buildozer & Dependencies
      run: |
        pip install --upgrade pip
        pip install cython virtualenv
        pip install buildozer==1.5.0

    - name: Build APK
      run: |
        yes | buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
